exports.priceList = [
  "single1|35|40|Adulte(16+) Danse Individuelle",
  "champ1|45|50|Adulte(16+) Multi 3 danses",
  "schol1|65|70|Adulte(16+) Bourse d'étude",
  "single0|15|20|Junior(15-) Danse Individuelle",
  "champ0|20|25|Junior(15-) Multi 3 danses",
  "schol0|30|35|Junior(15-) Bourse d'étude",
  "solo1|50|55|Démonstration en solo (Adulte & Junior)",
  "friday1|70|75|BILLETS VENDREDI 1ère RANGÉE TABLE",
  "friday2|55|60|BILLETS VENDREDI 2e RANGÉE| x 55 $can = ",
  "friday0|25|30|BILLETS VENDREDI Juvénile + Junior 15 & -",
  "saturday1|70|75|BILLETS SAMEDI 1ère RANGÉE",
  "saturday2|55|60|BILLETS SAMEDI 2e RANGÉE| x 55 $can = ",
  "saturday0|25|30|BILLETS SAMEDI Juvénile + Junior 15 & -",
  "sunday1|25|30|BILLETS DIMANCHE Adulte",
  "sunday0|20|25|BILLETS DIMANCHE Juvénile + Junior 15 & -",
];

exports.early = () => {
  const today = new Date();
  const deadline = new Date("2023, 08, 6");
  return today <= deadline;
};

exports.levels = [
  "Débutant",
  "Bronze 1",
  "Bronze",
  "Argent 1",
  "Argent",
  "Or",
  "or 1",
  "Or Avancé",
];

exports.ages = ["JV", "JR", "JE", "A", "B", "C", "D", "E", "F"];

exports.danceStyles = ["smooth", "rhythm", "ballroom", "latin"];

exports.smooth = ["W", "T", "F", "VW", "PB"];

exports.rhythm = [
  "C",
  "R",
  "SW",
  "B",
  "M",
  "SAL",
  "ME",
  "BA",
  "H",
  "WCS",
  "SAM",
  "PD",
  "TA",
  "MI",
  "TV",
];

exports.ballroom = ["W", "T", "VW", "F", "Q"];

exports.latin = ["C", "S", "R", "PD", "J"];

exports.danceNames = {
  w: "Waltz",
  t: "Tango",
  f: "Foxtrot",
  vw: "Viennese",
  pb: "Peabody",
  c: "Chacha",
  r: "Rumba",
  sw: "Swing",
  b: "Bolero",
  m: "Mambo",
  sal: "Salsa",
  me: "Merengue",
  ba: "Bachata",
  h: "Hustle",
  wcs: "Coast",
  sam: "Samba",
  pd: "Paso",
  ta: "Argentine",
  mi: "Milonga",
  tv: "Vals",
  q: "Quickstep",
  s: "Samba",
  j: "Jive",
};

exports.countries = [
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius & Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos Islands",
  "Colombia",
  "Comoros (the)",
  "Congo (Democratic Republic)",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia (Asia)",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard & McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (North)",
  "Korea (South)",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Minor Outlying Islands",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent, Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia, South Sandwich Isl.",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands (U.K.)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

exports.states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "American Samoa",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Trust Territories",
  "Utah",
  "Vermont",
  "Virginia",
  "Virgin Islands",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

exports.provinces = [
  "Alberta",
  "Colombie Britannique",
  "Île du Prince Édouard",
  "Manitoba",
  "Nouveau Brunswick",
  "Nouvelle Écosse",
  "Nunavut",
  "Ontario",
  "Québec",
  "Saskatchewan",
  "Terre Neuve et Labrador",
  "Territoires du Nord Ouest",
  "Yukon",
];

exports.statesAbbr = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "AS",
  "CA",
  "CO",
  "CT",
  "DE",
  "DC",
  "FL",
  "GA",
  "GU",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "CM",
  "OH",
  "OK",
  "OR",
  "PA",
  "PR",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "TT",
  "UT",
  "VT",
  "VA",
  "VI",
  "WA",
  "WV",
  "WI",
  "WY",
];

exports.provAbbr = [
  "AB",
  "BC",
  "PE",
  "MB",
  "NB",
  "NS",
  "NU",
  "ON",
  "QC",
  "SK",
  "NL",
  "NT",
  "YT",
];
